/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.devsense.openapigenerator_demo.api;

import io.devsense.openapigenerator_demo.model.Pet;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-07-31T11:34:52.177804+05:30[Asia/Kolkata]", comments = "Generator version: 7.14.0")
@Validated
@Tag(name = "pets", description = "the pets API")
public interface PetsApi {

    default PetsApiDelegate getDelegate() {
        return new PetsApiDelegate() {};
    }

    /**
     * POST /pets : Create a pet
     *
     * @param pet  (optional)
     * @return Pet created (status code 201)
     */
    @Operation(
        operationId = "createPets",
        summary = "Create a pet",
        responses = {
            @ApiResponse(responseCode = "201", description = "Pet created")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/pets",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> createPets(
        @Parameter(name = "Pet", description = "") @Valid @RequestBody(required = false) @Nullable Pet pet
    ) {
        return getDelegate().createPets(pet);
    }


    /**
     * GET /pets : List all pets
     *
     * @param limit  (optional)
     * @return A paged array of pets (status code 200)
     */
    @Operation(
        operationId = "listPets",
        summary = "List all pets",
        tags = { "pets" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A paged array of pets", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Pet.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/pets",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Pet>> listPets(
        @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false) @Nullable Integer limit
    ) {
        return getDelegate().listPets(limit);
    }


    /**
     * GET /pets/{petId} : Info for a specific pet
     *
     * @param petId  (required)
     * @return Expected response to a valid request (status code 200)
     */
    @Operation(
        operationId = "showPetById",
        summary = "Info for a specific pet",
        responses = {
            @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Pet.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/pets/{petId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Pet> showPetById(
        @Parameter(name = "petId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("petId") Integer petId
    ) {
        return getDelegate().showPetById(petId);
    }

}
